import { colors, radii } from '../theme';
import { commonStyles } from '../common';

export const manageProfilesStyles = {
  container: commonStyles.pageContainer,
  pageTitle: commonStyles.pageTitle,
  pageSubtitle: {
    color: colors.textMuted,
    fontSize: '14px',
    mt: 0.5,
  },
  searchBarContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 2,
    mb: 4,
  },
  searchField: {
    bgcolor: colors.bgCard,
    flexGrow: 1,
    maxWidth: '70%',
    '& .MuiOutlinedInput-root': {
      height: '42px',
      borderRadius: radii.md,
      border: `2px solid ${colors.border}`,
      '& fieldset': { border: 'none' },
    },
  },
  addButton: {
    ...commonStyles.primaryButton,
    px: 3,
    height: '42px',
  },
  tableCard: {
    ...commonStyles.borderedCard,
    overflow: 'hidden',
  },
  tableHead: commonStyles.tableHead,
  tableRow: {
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    '&:hover': {
      bgcolor: colors.bgHighlight,
    },
    '& .MuiTableCell-body': {
      py: 2.5,
      borderBottom: `1px solid ${colors.borderMuted}`,
      color: colors.textDark,
      fontSize: '16px',
    },
    '&:last-child .MuiTableCell-body': {
      borderBottom: 'none',
    },
  },
  tableCellName: {
    fontWeight: 600,
    color: colors.navy,
    fontSize: '16px',
  },
  tableCellMuted: {
    color: colors.textGray,
    fontSize: '16px',
  },
  tableCellRole: {
    fontWeight: 600,
    color: colors.primary,
    fontSize: '16px',
  },
  emptyCell: {
    py: 4,
    color: colors.textMuted,
    textAlign: 'center',
    fontSize: '16px',
  },
  paginationContainer: commonStyles.paginationContainer,
  pageBtn: commonStyles.pageBtn,
  activePageBtn: commonStyles.activePageBtn,
  pageEllipsis: commonStyles.pageEllipsis,
  filterCard: {
    ...commonStyles.borderedCard,
    p: 2.5,
  },
  filterHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    mb: 3,
    borderBottom: `1px solid ${colors.borderMuted}`,
    pb: 1,
  },
  filterIcon: {
    color: colors.primary,
    fontSize: 20,
  },
  filterTitle: {
    fontWeight: 700,
    color: colors.navy,
    fontSize: '16px',
  },
  filterLabel: {
    fontWeight: 700,
    fontSize: '13px',
    color: colors.navy,
    mb: 1,
  },
  filterOutlineBtn: {
    flex: 1,
    bgcolor: colors.bgCard,
    border: `1px solid ${colors.borderLight}`,
    borderRadius: radii.sm,
    color: colors.textGray,
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '13px',
    height: '34px',
    '&:hover': { bgcolor: colors.bgHighlight, borderColor: colors.border },
  },
  filterActiveBtn: {
    flex: 1,
    bgcolor: colors.bgHighlight,
    border: `2px solid ${colors.border}`,
    borderRadius: radii.sm,
    color: colors.primary,
    textTransform: 'none',
    fontWeight: 700,
    fontSize: '13px',
    height: '34px',
    '&:hover': { bgcolor: colors.bgHover },
  },
  selectInput: {
    borderRadius: radii.sm,
    border: `1px solid ${colors.borderLight}`,
    bgcolor: colors.bgCard,
    height: '36px',
    fontSize: '13px',
    color: '#333333',
    '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '&:hover': { borderColor: colors.border },
  },
  filterRoleBtn: {
    width: '100%',
    justifyContent: 'flex-start',
    bgcolor: colors.bgCard,
    border: `1px solid ${colors.borderLight}`,
    borderRadius: radii.sm,
    color: colors.textGray,
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '13px',
    py: 1,
    px: 2,
    '&:hover': { bgcolor: colors.bgHighlight, borderColor: colors.border },
  },
  filterRoleActiveBtn: {
    width: '100%',
    justifyContent: 'flex-start',
    bgcolor: colors.bgHighlight,
    border: `2px solid ${colors.border}`,
    borderRadius: radii.sm,
    color: colors.primary,
    textTransform: 'none',
    fontWeight: 700,
    fontSize: '13px',
    py: 1,
    px: 2,
    '&:hover': { bgcolor: colors.bgHover },
  },
  searchIcon: {
    color: colors.border,
  },
};
