import { colors, gradients, radii } from '../theme';
import { commonStyles } from '../common';

export const profileStyles = {
  pageContainer: {
    width: '100%',
    maxWidth: '100%',
    minHeight: '100vh',
    bgcolor: colors.bgPage,
    boxSizing: 'border-box',
  },
  pageHeader: {
    display: 'flex',
    bgcolor: colors.bgLayout,
    color: colors.navy,
    p: 2,
    height: 40,
    alignItems: 'end',
  },
  profileCard: {
    borderRadius: radii.xl,
    overflow: 'hidden',
    boxShadow: '0px 10px 40px rgba(0,0,0,0.08)',
    backgroundColor: colors.bgCard,
    my: 1,
  },
  cardHeader: {
    ...commonStyles.gradientHeader,
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    p: 3,
    flexWrap: 'wrap',
    minHeight: '120px',
  },
  actions: {
    textAlign: 'center',
    display: 'flex',
    justifyContent: 'center',
    gap: 2,
    flexWrap: 'wrap',
  },

  saveButton: {
    background: gradients.header,
    color: colors.white,
    px: 6,
    py: 1.5,
    borderRadius: radii.lg,
    textTransform: 'none',
    fontSize: '16px',
    fontWeight: 600,
    '&:hover': {
      background: gradients.header,
      filter: 'brightness(0.92)',
    },
    '&.Mui-disabled': {
      background: gradients.headerDisabled,
      color: colors.navy,
      opacity: 1,
      WebkitTextFillColor: colors.navy,
    },
    marginBottom: '35px',
  },

  cancelButton: {
    px: 4,
    py: 1.5,
    borderRadius: radii.lg,
    textTransform: 'none',
    fontSize: '16px',
    fontWeight: 600,
    border: `2px solid ${colors.border}`,
    color: colors.primary,
    bgcolor: colors.bgCard,
    boxShadow: 'none',
    marginBottom: '35px',
    '&:hover': {
      bgcolor: colors.bgHighlight,
      borderColor: colors.primary,
      boxShadow: 'none',
    },
  },
  avatar: {
    bgcolor: 'rgba(255,255,255,0.2)',
    my: { xs: 2, sm: 5 },
    mx: { xs: 2, sm: 7 },
    border: '2px solid rgba(255,255,255,0.4)',
    transform: { xs: 'scale(1.4)', sm: 'scale(1.7)', md: 'scale(2)' },
  },
  nameContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 1,
    minWidth: '200px',
    height: 'auto',
  },
  userName: {
    fontWeight: 500,
    color: colors.white,
    margin: '10px 0px 2px 0px',
    lineHeight: 1.2,
  },
  userRole: {
    fontWeight: 300,
    color: colors.roleAccent,
  },
  fieldLabelBox: commonStyles.fieldLabelBox,
  fieldLabelIcon: commonStyles.fieldLabelIcon,
  fieldLabelText: commonStyles.fieldLabelText,
  textField: commonStyles.textField,
  textFieldDisabled: commonStyles.textFieldDisabled,
};
