"""initial_schema

Revision ID: 0afbc3238ca4
Revises: e8289993ef42
Create Date: 2026-05-25 03:00:59.327590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afbc3238ca4'
down_revision: Union[str, Sequence[str], None] = 'e8289993ef42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'max_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'max_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
