"""initial_schema

Revision ID: 378a3318cbec
Revises: 0afbc3238ca4
Create Date: 2026-05-25 05:33:27.368457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '378a3318cbec'
down_revision: Union[str, Sequence[str], None] = '0afbc3238ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_shift_schedule_uc', 'shift_schedule', ['shift_id', 'schedule_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_schedule', sa.Column('shift_archive_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('shift_schedule_shift_archive_id_fkey'), 'shift_schedule', 'shift_archive', ['shift_archive_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_shift_schedule_uc', 'shift_schedule', type_='unique')
    op.create_table('shift_user_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_archive.id'], name=op.f('shift_user_archive_shift_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('shift_user_archive_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_user_archive_pkey'))
    )
    op.create_table('shift_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['shift_type.id'], name=op.f('shift_archive_type_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_archive_pkey'))
    )
    # ### end Alembic commands ###
