"""rename_shift_columns

Revision ID: 8f1b998f9681
Revises: e727ecbcdc92
Create Date: 2026-05-24 02:41:07.389681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f1b998f9681'
down_revision: Union[str, Sequence[str], None] = 'e727ecbcdc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.drop_column('shift', 'end_date')
    op.alter_column('shift_type', 'rate',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('shift_type', 'increased_payment',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('shift_type', 'increased_payment',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('shift_type', 'rate',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('shift', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('shift', 'end_time')
    # ### end Alembic commands ###
