"""initial_schema

Revision ID: e8289993ef42
Revises: 8f1b998f9681
Create Date: 2026-05-25 02:48:11.125256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8289993ef42'
down_revision: Union[str, Sequence[str], None] = '8f1b998f9681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('max_user', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift', 'max_user')
    # ### end Alembic commands ###
